import type { ArticleCandidate, Compiler, CompiledArticle } from '../types.js';

/**
 * v1 deterministic compiler. Produces a CompiledArticle per ArticleCandidate
 * with:
 *   - kebab-case slug from title
 *   - body = candidate.text verbatim (markdown preserved, plain text wrapped)
 *   - cross-references derived from substring matching of other article titles
 *     in the body (case-insensitive, word-boundary)
 *
 * v2 will swap this for a 0G Compute-backed compiler that uses TEE-attested
 * inference to rewrite each candidate as a focused Karpathy-style wiki article
 * with explicit cross-references generated by the LLM, not by string match.
 */
export const deterministicCompiler: Compiler = {
  name: 'deterministic-v1',
  async compile(candidates: ArticleCandidate[]): Promise<CompiledArticle[]> {
    const now = new Date().toISOString();

    // First pass: assign slugs, ensuring uniqueness.
    const used = new Set<string>();
    const slugged = candidates.map((c) => {
      let slug = slugify(c.title);
      if (slug.length === 0) slug = 'untitled';
      let unique = slug;
      let n = 2;
      while (used.has(unique)) unique = `${slug}-${n++}`;
      used.add(unique);
      return { ...c, slug: unique };
    });

    // Second pass: build links by scanning each article's body for the titles
    // of all OTHER articles. Case-insensitive, longest-title-first so
    // "Mixture of Brains" wins over "Brains".
    const sortedByTitleLen = [...slugged].sort((a, b) => b.title.length - a.title.length);

    return slugged.map((article) => {
      const links: string[] = [];
      const bodyLower = article.text.toLowerCase();
      for (const other of sortedByTitleLen) {
        if (other.slug === article.slug) continue;
        const needle = other.title.toLowerCase();
        if (needle.length < 4) continue; // skip noisy short titles
        if (bodyLower.includes(needle) && !links.includes(other.slug)) {
          links.push(other.slug);
        }
      }

      return {
        slug: article.slug,
        title: article.title,
        body: article.text,
        links,
        sources: [...new Set(article.sources.map((s) => s.path))],
        updatedAt: now,
      };
    });
  },
};

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}
